Description: Role that will be assumed by CircleCI Pipeline
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AuditAccountNumber:
    Type: Number
    Description: "Audit account number"
Resources:
  CrossAccountPipelineDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AuditAccountNumber}:root"
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: PipelineRole